// proto/ingestion.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ingestion.proto

package ingestion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ClientBookId  string                 `protobuf:"bytes,2,opt,name=client_book_id,json=clientBookId,proto3" json:"client_book_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	DocType       string                 `protobuf:"bytes,4,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`                                                                                 // invoice | bank_statement | gl_export
	ColumnMap     map[string]string      `protobuf:"bytes,5,rep,name=column_map,json=columnMap,proto3" json:"column_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // per-book CSV column mapping (doc 08 §1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ProcessDocumentRequest) GetClientBookId() string {
	if x != nil {
		return x.ClientBookId
	}
	return ""
}

func (x *ProcessDocumentRequest) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *ProcessDocumentRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *ProcessDocumentRequest) GetColumnMap() map[string]string {
	if x != nil {
		return x.ColumnMap
	}
	return nil
}

type ProcessDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*ExtractedEntity     `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessDocumentResponse) GetEntities() []*ExtractedEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ExtractedEntity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntityType      string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // invoice_line_item | bank_transaction | gl_entry
	AmountCents     int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency        string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionDate string                 `protobuf:"bytes,4,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	Counterparty    string                 `protobuf:"bytes,5,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	GlAccountCode   string                 `protobuf:"bytes,7,opt,name=gl_account_code,json=glAccountCode,proto3" json:"gl_account_code,omitempty"`
	PageNumber      int32                  `protobuf:"varint,8,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Bbox            *BoundingBox           `protobuf:"bytes,9,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Confidence      float64                `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SourceFormat    string                 `protobuf:"bytes,11,opt,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty"`       // ocr | structured
	EntitySubtype   string                 `protobuf:"bytes,12,opt,name=entity_subtype,json=entitySubtype,proto3" json:"entity_subtype,omitempty"`    // standard | credit_note | refund | void
	TransactionRef  string                 `protobuf:"bytes,13,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"` // source transaction reference (GL Num, OFX FITID)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtractedEntity) Reset() {
	*x = ExtractedEntity{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedEntity) ProtoMessage() {}

func (x *ExtractedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedEntity.ProtoReflect.Descriptor instead.
func (*ExtractedEntity) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractedEntity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ExtractedEntity) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *ExtractedEntity) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ExtractedEntity) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *ExtractedEntity) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *ExtractedEntity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtractedEntity) GetGlAccountCode() string {
	if x != nil {
		return x.GlAccountCode
	}
	return ""
}

func (x *ExtractedEntity) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ExtractedEntity) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *ExtractedEntity) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExtractedEntity) GetSourceFormat() string {
	if x != nil {
		return x.SourceFormat
	}
	return ""
}

func (x *ExtractedEntity) GetEntitySubtype() string {
	if x != nil {
		return x.EntitySubtype
	}
	return ""
}

func (x *ExtractedEntity) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *BoundingBox) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_ingestion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\tingestion\"\xaa\x02\n" +
	"\x16ProcessDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12$\n" +
	"\x0eclient_book_id\x18\x02 \x01(\tR\fclientBookId\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\x12\x19\n" +
	"\bdoc_type\x18\x04 \x01(\tR\adocType\x12O\n" +
	"\n" +
	"column_map\x18\x05 \x03(\v20.ingestion.ProcessDocumentRequest.ColumnMapEntryR\tcolumnMap\x1a<\n" +
	"\x0eColumnMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x17ProcessDocumentResponse\x126\n" +
	"\bentities\x18\x01 \x03(\v2\x1a.ingestion.ExtractedEntityR\bentities\"\xec\x03\n" +
	"\x0fExtractedEntity\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12)\n" +
	"\x10transaction_date\x18\x04 \x01(\tR\x0ftransactionDate\x12\"\n" +
	"\fcounterparty\x18\x05 \x01(\tR\fcounterparty\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12&\n" +
	"\x0fgl_account_code\x18\a \x01(\tR\rglAccountCode\x12\x1f\n" +
	"\vpage_number\x18\b \x01(\x05R\n" +
	"pageNumber\x12*\n" +
	"\x04bbox\x18\t \x01(\v2\x16.ingestion.BoundingBoxR\x04bbox\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rsource_format\x18\v \x01(\tR\fsourceFormat\x12%\n" +
	"\x0eentity_subtype\x18\f \x01(\tR\rentitySubtype\x12'\n" +
	"\x0ftransaction_ref\x18\r \x01(\tR\x0etransactionRef\"W\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\"0\n" +
	"\rStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"e\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress2\xb8\x01\n" +
	"\x10IngestionService\x12X\n" +
	"\x0fProcessDocument\x12!.ingestion.ProcessDocumentRequest\x1a\".ingestion.ProcessDocumentResponse\x12J\n" +
	"\x13GetProcessingStatus\x12\x18.ingestion.StatusRequest\x1a\x19.ingestion.StatusResponseBCZAgithub.com/tanzeelgcuf/ai-auditor/services/api/genproto/ingestionb\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ingestion_proto_goTypes = []any{
	(*ProcessDocumentRequest)(nil),  // 0: ingestion.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 1: ingestion.ProcessDocumentResponse
	(*ExtractedEntity)(nil),         // 2: ingestion.ExtractedEntity
	(*BoundingBox)(nil),             // 3: ingestion.BoundingBox
	(*StatusRequest)(nil),           // 4: ingestion.StatusRequest
	(*StatusResponse)(nil),          // 5: ingestion.StatusResponse
	nil,                             // 6: ingestion.ProcessDocumentRequest.ColumnMapEntry
}
var file_ingestion_proto_depIdxs = []int32{
	6, // 0: ingestion.ProcessDocumentRequest.column_map:type_name -> ingestion.ProcessDocumentRequest.ColumnMapEntry
	2, // 1: ingestion.ProcessDocumentResponse.entities:type_name -> ingestion.ExtractedEntity
	3, // 2: ingestion.ExtractedEntity.bbox:type_name -> ingestion.BoundingBox
	0, // 3: ingestion.IngestionService.ProcessDocument:input_type -> ingestion.ProcessDocumentRequest
	4, // 4: ingestion.IngestionService.GetProcessingStatus:input_type -> ingestion.StatusRequest
	1, // 5: ingestion.IngestionService.ProcessDocument:output_type -> ingestion.ProcessDocumentResponse
	5, // 6: ingestion.IngestionService.GetProcessingStatus:output_type -> ingestion.StatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
