// proto/verification.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: verification.proto

package verification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReconciliationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientBookId       string                 `protobuf:"bytes,1,opt,name=client_book_id,json=clientBookId,proto3" json:"client_book_id,omitempty"`
	InvoiceAmountCents int64                  `protobuf:"varint,2,opt,name=invoice_amount_cents,json=invoiceAmountCents,proto3" json:"invoice_amount_cents,omitempty"`
	BankAmountCents    int64                  `protobuf:"varint,3,opt,name=bank_amount_cents,json=bankAmountCents,proto3" json:"bank_amount_cents,omitempty"`
	GlAmountCents      int64                  `protobuf:"varint,4,opt,name=gl_amount_cents,json=glAmountCents,proto3" json:"gl_amount_cents,omitempty"`
	ToleranceCents     int32                  `protobuf:"varint,5,opt,name=tolerance_cents,json=toleranceCents,proto3" json:"tolerance_cents,omitempty"`
	HasInvoice         bool                   `protobuf:"varint,6,opt,name=has_invoice,json=hasInvoice,proto3" json:"has_invoice,omitempty"` // leg present (false => exclude from variance)
	HasBank            bool                   `protobuf:"varint,7,opt,name=has_bank,json=hasBank,proto3" json:"has_bank,omitempty"`
	HasGl              bool                   `protobuf:"varint,8,opt,name=has_gl,json=hasGl,proto3" json:"has_gl,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReconciliationRequest) Reset() {
	*x = ReconciliationRequest{}
	mi := &file_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationRequest) ProtoMessage() {}

func (x *ReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationRequest.ProtoReflect.Descriptor instead.
func (*ReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

func (x *ReconciliationRequest) GetClientBookId() string {
	if x != nil {
		return x.ClientBookId
	}
	return ""
}

func (x *ReconciliationRequest) GetInvoiceAmountCents() int64 {
	if x != nil {
		return x.InvoiceAmountCents
	}
	return 0
}

func (x *ReconciliationRequest) GetBankAmountCents() int64 {
	if x != nil {
		return x.BankAmountCents
	}
	return 0
}

func (x *ReconciliationRequest) GetGlAmountCents() int64 {
	if x != nil {
		return x.GlAmountCents
	}
	return 0
}

func (x *ReconciliationRequest) GetToleranceCents() int32 {
	if x != nil {
		return x.ToleranceCents
	}
	return 0
}

func (x *ReconciliationRequest) GetHasInvoice() bool {
	if x != nil {
		return x.HasInvoice
	}
	return false
}

func (x *ReconciliationRequest) GetHasBank() bool {
	if x != nil {
		return x.HasBank
	}
	return false
}

func (x *ReconciliationRequest) GetHasGl() bool {
	if x != nil {
		return x.HasGl
	}
	return false
}

type ReconciliationResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VarianceCents      int64                  `protobuf:"varint,1,opt,name=variance_cents,json=varianceCents,proto3" json:"variance_cents,omitempty"`
	ExceedsTolerance   bool                   `protobuf:"varint,2,opt,name=exceeds_tolerance,json=exceedsTolerance,proto3" json:"exceeds_tolerance,omitempty"`
	CalculationFormula string                 `protobuf:"bytes,3,opt,name=calculation_formula,json=calculationFormula,proto3" json:"calculation_formula,omitempty"`
	RuleId             string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleVersion        string                 `protobuf:"bytes,5,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	Severity           string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"` // info | low | medium | high
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReconciliationResult) Reset() {
	*x = ReconciliationResult{}
	mi := &file_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationResult) ProtoMessage() {}

func (x *ReconciliationResult) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationResult.ProtoReflect.Descriptor instead.
func (*ReconciliationResult) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{1}
}

func (x *ReconciliationResult) GetVarianceCents() int64 {
	if x != nil {
		return x.VarianceCents
	}
	return 0
}

func (x *ReconciliationResult) GetExceedsTolerance() bool {
	if x != nil {
		return x.ExceedsTolerance
	}
	return false
}

func (x *ReconciliationResult) GetCalculationFormula() string {
	if x != nil {
		return x.CalculationFormula
	}
	return ""
}

func (x *ReconciliationResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ReconciliationResult) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *ReconciliationResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type BatchReconciliationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientBookId  string                 `protobuf:"bytes,1,opt,name=client_book_id,json=clientBookId,proto3" json:"client_book_id,omitempty"`
	Groups        []*GroupReconciliation `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReconciliationRequest) Reset() {
	*x = BatchReconciliationRequest{}
	mi := &file_verification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReconciliationRequest) ProtoMessage() {}

func (x *BatchReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReconciliationRequest.ProtoReflect.Descriptor instead.
func (*BatchReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{2}
}

func (x *BatchReconciliationRequest) GetClientBookId() string {
	if x != nil {
		return x.ClientBookId
	}
	return ""
}

func (x *BatchReconciliationRequest) GetGroups() []*GroupReconciliation {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupReconciliation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupId           string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InvoiceTotalCents int64                  `protobuf:"varint,2,opt,name=invoice_total_cents,json=invoiceTotalCents,proto3" json:"invoice_total_cents,omitempty"`
	BankTotalCents    int64                  `protobuf:"varint,3,opt,name=bank_total_cents,json=bankTotalCents,proto3" json:"bank_total_cents,omitempty"`
	GlTotalCents      int64                  `protobuf:"varint,4,opt,name=gl_total_cents,json=glTotalCents,proto3" json:"gl_total_cents,omitempty"`
	ToleranceCents    int32                  `protobuf:"varint,5,opt,name=tolerance_cents,json=toleranceCents,proto3" json:"tolerance_cents,omitempty"`
	HasInvoice        bool                   `protobuf:"varint,6,opt,name=has_invoice,json=hasInvoice,proto3" json:"has_invoice,omitempty"` // leg present (false => exclude from variance)
	HasBank           bool                   `protobuf:"varint,7,opt,name=has_bank,json=hasBank,proto3" json:"has_bank,omitempty"`
	HasGl             bool                   `protobuf:"varint,8,opt,name=has_gl,json=hasGl,proto3" json:"has_gl,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupReconciliation) Reset() {
	*x = GroupReconciliation{}
	mi := &file_verification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReconciliation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReconciliation) ProtoMessage() {}

func (x *GroupReconciliation) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReconciliation.ProtoReflect.Descriptor instead.
func (*GroupReconciliation) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{3}
}

func (x *GroupReconciliation) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupReconciliation) GetInvoiceTotalCents() int64 {
	if x != nil {
		return x.InvoiceTotalCents
	}
	return 0
}

func (x *GroupReconciliation) GetBankTotalCents() int64 {
	if x != nil {
		return x.BankTotalCents
	}
	return 0
}

func (x *GroupReconciliation) GetGlTotalCents() int64 {
	if x != nil {
		return x.GlTotalCents
	}
	return 0
}

func (x *GroupReconciliation) GetToleranceCents() int32 {
	if x != nil {
		return x.ToleranceCents
	}
	return 0
}

func (x *GroupReconciliation) GetHasInvoice() bool {
	if x != nil {
		return x.HasInvoice
	}
	return false
}

func (x *GroupReconciliation) GetHasBank() bool {
	if x != nil {
		return x.HasBank
	}
	return false
}

func (x *GroupReconciliation) GetHasGl() bool {
	if x != nil {
		return x.HasGl
	}
	return false
}

type BatchReconciliationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GroupResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReconciliationResult) Reset() {
	*x = BatchReconciliationResult{}
	mi := &file_verification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReconciliationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReconciliationResult) ProtoMessage() {}

func (x *BatchReconciliationResult) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReconciliationResult.ProtoReflect.Descriptor instead.
func (*BatchReconciliationResult) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{4}
}

func (x *BatchReconciliationResult) GetResults() []*GroupResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GroupResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GroupId            string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	VarianceCents      int64                  `protobuf:"varint,2,opt,name=variance_cents,json=varianceCents,proto3" json:"variance_cents,omitempty"`
	ExceedsTolerance   bool                   `protobuf:"varint,3,opt,name=exceeds_tolerance,json=exceedsTolerance,proto3" json:"exceeds_tolerance,omitempty"`
	CalculationFormula string                 `protobuf:"bytes,4,opt,name=calculation_formula,json=calculationFormula,proto3" json:"calculation_formula,omitempty"`
	RuleId             string                 `protobuf:"bytes,5,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleVersion        string                 `protobuf:"bytes,6,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	Severity           string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupResult) Reset() {
	*x = GroupResult{}
	mi := &file_verification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResult) ProtoMessage() {}

func (x *GroupResult) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResult.ProtoReflect.Descriptor instead.
func (*GroupResult) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{5}
}

func (x *GroupResult) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupResult) GetVarianceCents() int64 {
	if x != nil {
		return x.VarianceCents
	}
	return 0
}

func (x *GroupResult) GetExceedsTolerance() bool {
	if x != nil {
		return x.ExceedsTolerance
	}
	return false
}

func (x *GroupResult) GetCalculationFormula() string {
	if x != nil {
		return x.CalculationFormula
	}
	return ""
}

func (x *GroupResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GroupResult) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *GroupResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

var File_verification_proto protoreflect.FileDescriptor

const file_verification_proto_rawDesc = "" +
	"\n" +
	"\x12verification.proto\x12\fverification\"\xbf\x02\n" +
	"\x15ReconciliationRequest\x12$\n" +
	"\x0eclient_book_id\x18\x01 \x01(\tR\fclientBookId\x120\n" +
	"\x14invoice_amount_cents\x18\x02 \x01(\x03R\x12invoiceAmountCents\x12*\n" +
	"\x11bank_amount_cents\x18\x03 \x01(\x03R\x0fbankAmountCents\x12&\n" +
	"\x0fgl_amount_cents\x18\x04 \x01(\x03R\rglAmountCents\x12'\n" +
	"\x0ftolerance_cents\x18\x05 \x01(\x05R\x0etoleranceCents\x12\x1f\n" +
	"\vhas_invoice\x18\x06 \x01(\bR\n" +
	"hasInvoice\x12\x19\n" +
	"\bhas_bank\x18\a \x01(\bR\ahasBank\x12\x15\n" +
	"\x06has_gl\x18\b \x01(\bR\x05hasGl\"\xf3\x01\n" +
	"\x14ReconciliationResult\x12%\n" +
	"\x0evariance_cents\x18\x01 \x01(\x03R\rvarianceCents\x12+\n" +
	"\x11exceeds_tolerance\x18\x02 \x01(\bR\x10exceedsTolerance\x12/\n" +
	"\x13calculation_formula\x18\x03 \x01(\tR\x12calculationFormula\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12!\n" +
	"\frule_version\x18\x05 \x01(\tR\vruleVersion\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\"}\n" +
	"\x1aBatchReconciliationRequest\x12$\n" +
	"\x0eclient_book_id\x18\x01 \x01(\tR\fclientBookId\x129\n" +
	"\x06groups\x18\x02 \x03(\v2!.verification.GroupReconciliationR\x06groups\"\xac\x02\n" +
	"\x13GroupReconciliation\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12.\n" +
	"\x13invoice_total_cents\x18\x02 \x01(\x03R\x11invoiceTotalCents\x12(\n" +
	"\x10bank_total_cents\x18\x03 \x01(\x03R\x0ebankTotalCents\x12$\n" +
	"\x0egl_total_cents\x18\x04 \x01(\x03R\fglTotalCents\x12'\n" +
	"\x0ftolerance_cents\x18\x05 \x01(\x05R\x0etoleranceCents\x12\x1f\n" +
	"\vhas_invoice\x18\x06 \x01(\bR\n" +
	"hasInvoice\x12\x19\n" +
	"\bhas_bank\x18\a \x01(\bR\ahasBank\x12\x15\n" +
	"\x06has_gl\x18\b \x01(\bR\x05hasGl\"P\n" +
	"\x19BatchReconciliationResult\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.verification.GroupResultR\aresults\"\x85\x02\n" +
	"\vGroupResult\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12%\n" +
	"\x0evariance_cents\x18\x02 \x01(\x03R\rvarianceCents\x12+\n" +
	"\x11exceeds_tolerance\x18\x03 \x01(\bR\x10exceedsTolerance\x12/\n" +
	"\x13calculation_formula\x18\x04 \x01(\tR\x12calculationFormula\x12\x17\n" +
	"\arule_id\x18\x05 \x01(\tR\x06ruleId\x12!\n" +
	"\frule_version\x18\x06 \x01(\tR\vruleVersion\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity2\xdc\x01\n" +
	"\x13VerificationService\x12a\n" +
	"\x16EvaluateReconciliation\x12#.verification.ReconciliationRequest\x1a\".verification.ReconciliationResult\x12b\n" +
	"\rBatchEvaluate\x12(.verification.BatchReconciliationRequest\x1a'.verification.BatchReconciliationResultBFZDgithub.com/tanzeelgcuf/ai-auditor/services/api/genproto/verificationb\x06proto3"

var (
	file_verification_proto_rawDescOnce sync.Once
	file_verification_proto_rawDescData []byte
)

func file_verification_proto_rawDescGZIP() []byte {
	file_verification_proto_rawDescOnce.Do(func() {
		file_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verification_proto_rawDesc), len(file_verification_proto_rawDesc)))
	})
	return file_verification_proto_rawDescData
}

var file_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_verification_proto_goTypes = []any{
	(*ReconciliationRequest)(nil),      // 0: verification.ReconciliationRequest
	(*ReconciliationResult)(nil),       // 1: verification.ReconciliationResult
	(*BatchReconciliationRequest)(nil), // 2: verification.BatchReconciliationRequest
	(*GroupReconciliation)(nil),        // 3: verification.GroupReconciliation
	(*BatchReconciliationResult)(nil),  // 4: verification.BatchReconciliationResult
	(*GroupResult)(nil),                // 5: verification.GroupResult
}
var file_verification_proto_depIdxs = []int32{
	3, // 0: verification.BatchReconciliationRequest.groups:type_name -> verification.GroupReconciliation
	5, // 1: verification.BatchReconciliationResult.results:type_name -> verification.GroupResult
	0, // 2: verification.VerificationService.EvaluateReconciliation:input_type -> verification.ReconciliationRequest
	2, // 3: verification.VerificationService.BatchEvaluate:input_type -> verification.BatchReconciliationRequest
	1, // 4: verification.VerificationService.EvaluateReconciliation:output_type -> verification.ReconciliationResult
	4, // 5: verification.VerificationService.BatchEvaluate:output_type -> verification.BatchReconciliationResult
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_verification_proto_init() }
func file_verification_proto_init() {
	if File_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verification_proto_rawDesc), len(file_verification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verification_proto_goTypes,
		DependencyIndexes: file_verification_proto_depIdxs,
		MessageInfos:      file_verification_proto_msgTypes,
	}.Build()
	File_verification_proto = out.File
	file_verification_proto_goTypes = nil
	file_verification_proto_depIdxs = nil
}
